/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TabsAppearanceRouteImport } from './routes/_tabs/appearance'
import { Route as TabsCoursesRouteImport } from './routes/_tabs/courses'
import { Route as TabsLearningRouteImport } from './routes/_tabs/learning'
import { Route as TabsMeRouteImport } from './routes/_tabs/me'
import { Route as TabsNotificationsRouteImport } from './routes/_tabs/notifications'
import { Route as TabsPrivacyRouteImport } from './routes/_tabs/privacy'
import { Route as TabsStreakRouteImport } from './routes/_tabs/streak'
import { Route as TabsSubjectCourseIdRouteImport } from './routes/_tabs/subject.$courseId'
import { Route as ApiPublicCoursePdfRouteImport } from './routes/api/public/course-pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsAppearanceRoute = TabsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => TabsRoute,
} as any)
const TabsCoursesRoute = TabsCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => TabsRoute,
} as any)
const TabsLearningRoute = TabsLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => TabsRoute,
} as any)
const TabsMeRoute = TabsMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => TabsRoute,
} as any)
const TabsNotificationsRoute = TabsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => TabsRoute,
} as any)
const TabsPrivacyRoute = TabsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => TabsRoute,
} as any)
const TabsStreakRoute = TabsStreakRouteImport.update({
  id: '/streak',
  path: '/streak',
  getParentRoute: () => TabsRoute,
} as any)
const TabsSubjectCourseIdRoute = TabsSubjectCourseIdRouteImport.update({
  id: '/subject/$courseId',
  path: '/subject/$courseId',
  getParentRoute: () => TabsRoute,
} as any)
const ApiPublicCoursePdfRoute = ApiPublicCoursePdfRouteImport.update({
  id: '/api/public/course-pdf',
  path: '/api/public/course-pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/appearance': typeof TabsAppearanceRoute
  '/courses': typeof TabsCoursesRoute
  '/learning': typeof TabsLearningRoute
  '/me': typeof TabsMeRoute
  '/notifications': typeof TabsNotificationsRoute
  '/privacy': typeof TabsPrivacyRoute
  '/streak': typeof TabsStreakRoute
  '/subject/$courseId': typeof TabsSubjectCourseIdRoute
  '/api/public/course-pdf': typeof ApiPublicCoursePdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/appearance': typeof TabsAppearanceRoute
  '/courses': typeof TabsCoursesRoute
  '/learning': typeof TabsLearningRoute
  '/me': typeof TabsMeRoute
  '/notifications': typeof TabsNotificationsRoute
  '/privacy': typeof TabsPrivacyRoute
  '/streak': typeof TabsStreakRoute
  '/subject/$courseId': typeof TabsSubjectCourseIdRoute
  '/api/public/course-pdf': typeof ApiPublicCoursePdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tabs': typeof TabsRouteWithChildren
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/_tabs/appearance': typeof TabsAppearanceRoute
  '/_tabs/courses': typeof TabsCoursesRoute
  '/_tabs/learning': typeof TabsLearningRoute
  '/_tabs/me': typeof TabsMeRoute
  '/_tabs/notifications': typeof TabsNotificationsRoute
  '/_tabs/privacy': typeof TabsPrivacyRoute
  '/_tabs/streak': typeof TabsStreakRoute
  '/_tabs/subject/$courseId': typeof TabsSubjectCourseIdRoute
  '/api/public/course-pdf': typeof ApiPublicCoursePdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/faq'
    | '/login'
    | '/appearance'
    | '/courses'
    | '/learning'
    | '/me'
    | '/notifications'
    | '/privacy'
    | '/streak'
    | '/subject/$courseId'
    | '/api/public/course-pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/faq'
    | '/login'
    | '/appearance'
    | '/courses'
    | '/learning'
    | '/me'
    | '/notifications'
    | '/privacy'
    | '/streak'
    | '/subject/$courseId'
    | '/api/public/course-pdf'
  id:
    | '__root__'
    | '/'
    | '/_tabs'
    | '/about'
    | '/faq'
    | '/login'
    | '/_tabs/appearance'
    | '/_tabs/courses'
    | '/_tabs/learning'
    | '/_tabs/me'
    | '/_tabs/notifications'
    | '/_tabs/privacy'
    | '/_tabs/streak'
    | '/_tabs/subject/$courseId'
    | '/api/public/course-pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TabsRoute: typeof TabsRouteWithChildren
  AboutRoute: typeof AboutRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  ApiPublicCoursePdfRoute: typeof ApiPublicCoursePdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/appearance': {
      id: '/_tabs/appearance'
      path: '/appearance'
      fullPath: '/appearance'
      preLoaderRoute: typeof TabsAppearanceRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/courses': {
      id: '/_tabs/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof TabsCoursesRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/learning': {
      id: '/_tabs/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof TabsLearningRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/me': {
      id: '/_tabs/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof TabsMeRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/notifications': {
      id: '/_tabs/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof TabsNotificationsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/privacy': {
      id: '/_tabs/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof TabsPrivacyRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/streak': {
      id: '/_tabs/streak'
      path: '/streak'
      fullPath: '/streak'
      preLoaderRoute: typeof TabsStreakRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/subject/$courseId': {
      id: '/_tabs/subject/$courseId'
      path: '/subject/$courseId'
      fullPath: '/subject/$courseId'
      preLoaderRoute: typeof TabsSubjectCourseIdRouteImport
      parentRoute: typeof TabsRoute
    }
    '/api/public/course-pdf': {
      id: '/api/public/course-pdf'
      path: '/api/public/course-pdf'
      fullPath: '/api/public/course-pdf'
      preLoaderRoute: typeof ApiPublicCoursePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TabsRouteChildren {
  TabsAppearanceRoute: typeof TabsAppearanceRoute
  TabsCoursesRoute: typeof TabsCoursesRoute
  TabsLearningRoute: typeof TabsLearningRoute
  TabsMeRoute: typeof TabsMeRoute
  TabsNotificationsRoute: typeof TabsNotificationsRoute
  TabsPrivacyRoute: typeof TabsPrivacyRoute
  TabsStreakRoute: typeof TabsStreakRoute
  TabsSubjectCourseIdRoute: typeof TabsSubjectCourseIdRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsAppearanceRoute: TabsAppearanceRoute,
  TabsCoursesRoute: TabsCoursesRoute,
  TabsLearningRoute: TabsLearningRoute,
  TabsMeRoute: TabsMeRoute,
  TabsNotificationsRoute: TabsNotificationsRoute,
  TabsPrivacyRoute: TabsPrivacyRoute,
  TabsStreakRoute: TabsStreakRoute,
  TabsSubjectCourseIdRoute: TabsSubjectCourseIdRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TabsRoute: TabsRouteWithChildren,
  AboutRoute: AboutRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  ApiPublicCoursePdfRoute: ApiPublicCoursePdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
